### ISSUE TITLE
Force it not to Cache

### ISSUE THREAD

**Issue by mehatfie** [UWARG/WARG-Website#1]
Tried to do this myself but had failed.

Issue occurs where if someone has previously opened the webpage, it becomes cached. Therefore if you make any changes to the website and upload it.... the person won't see it because their browser is grabbing local data.... They would have to go and delete all cookies / cache / etc. in order to make the page refresh and collect your newest website.... which sucks

**Comment by sergei1152** [comment]
You can fix this with cache busting, where you basically append a different tag name at the end of a file to tell the browser the asset is different. So say you have a resource `" /styles.css"`, you can cache bust it by instead loading it with `"/styles.css?v=1"` . Then change the number at the end per iteration. 

Caching is always good since it speeds up subsequent visits to the website.
